GET {{host}}/system/user

### 登陆
GET {{host}}/login?username=a&passwd=2

> {%
  client.test("test",function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.body.code === 0, "code is not zero");
  client.global.set("token", encodeURIComponent(response.body.data.token));
  client.log("token: "+client.global.get("token"));
})
%}

###
GET {{host}}/system/user?token={{token}}

### 登出
GET {{host}}/user/logout?token={{token}}

###
GET {{host}}/user/info

